# Enable default datasource
quarkus.datasource.db-kind=oracle
quarkus.datasource.username=test
quarkus.datasource.password=test
#vault
quarkus.vault.devservices.enabled=true

# Optional: disable Dev Services if you want only Testcontainers JDBC
quarkus.datasource.devservices.enabled=true