quarkus.http.port=18080

quarkus.vault.secret-config-kv-path.foo_bar=acme/foobar
quarkus.vault.devservices.enabled=true
quarkus.vault.devservices.init-commands=kv put secret/acme/foobar 'foo=bar'
